### ISSUE TITLE
Support for self-signed certificates on keystone service

### ISSUE THREAD

**Issue by bgagnon** [wikimedia/search-repository-swift#11]
Currently throws an SSL exception::

```text
elasticsearch01_1 |     at org.wikimedia.elasticsearch.swift.repositories.SwiftService.swiftKeyStone(SwiftService.java:63)
elasticsearch01_1 |     at org.wikimedia.elasticsearch.swift.repositories.SwiftAccountFactory.createAccount(SwiftAccountFactory.java:9)
elasticsearch01_1 |     at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(SwiftRepository.java:65)
elasticsearch01_1 |     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
elasticsearch01_1 |     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
elasticsearch01_1 |     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
elasticsearch01_1 |     at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
elasticsearch01_1 |     at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
elasticsearch01_1 |     at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
elasticsearch01_1 |     at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
elasticsearch01_1 |     at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
elasticsearch01_1 |     at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
elasticsearch01_1 |     at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
elasticsearch01_1 |     at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
elasticsearch01_1 |     at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
elasticsearch01_1 |     at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
elasticsearch01_1 |     at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
elasticsearch01_1 |     at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
elasticsearch01_1 |     at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
elasticsearch01_1 |     at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
elasticsearch01_1 |     at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
elasticsearch01_1 |     ... 13 more
elasticsearch01_1 | Caused by: org.javaswift.joss.exception.CommandException: Unable to execute the HTTP call or to convert the HTTP Response
elasticsearch01_1 |     at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:58)
elasticsearch01_1 |     at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:98)
elasticsearch01_1 |     at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:27)
elasticsearch01_1 |     at org.javaswift.joss.client.core.AbstractClient.authenticate(AbstractClient.java:35)
elasticsearch01_1 |     at org.javaswift.joss.client.factory.AccountFactory.createAccount(AccountFactory.java:30)
elasticsearch01_1 |     at org.wikimedia.elasticsearch.swift.repositories.SwiftService.swiftKeyStone(SwiftService.java:61)
elasticsearch01_1 |     ... 33 more
elasticsearch01_1 | Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
elasticsearch01_1 |     at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
elasticsearch01_1 |     at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
elasticsearch01_1 |     at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
elasticsearch01_1 |     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
elasticsearch01_1 |     at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
elasticsearch01_1 |     at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
elasticsearch01_1 |     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
elasticsearch01_1 |     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
elasticsearch01_1 |     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
elasticsearch01_1 |     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
elasticsearch01_1 |     at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:49)
elasticsearch01_1 |     ... 38 more
```

**Comment by AtzeDeVries** [comment]
plus one for this.

**Comment by bgagnon** [comment]
The workaround we use is to create a new Java trust store (.jks) and pass it to Elasticsearch at initialization. We throw in all our internal certificates into this trust store using ``keytool``:

    keytool \
      -importcert \
      -file certificate.cer \
      -keystore /path/to/my_trust_store.jks -alias "host.name.domain"

Then pass it to Elasticsearch (or rather, to the JVM):

    JAVA_OPTS=-Djavax.net.ssl.trustStore=/path/to/my_trust_store.jks
