### ISSUE TITLE
Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement()

### ISSUE THREAD

**Issue by jlesaux** [wikimedia/search-repository-swift#20]
Hi,

I got errors using v2.3.3 of "search-repository-swift" (v1.6 and 1.7 works for me on others ES clusters) 

Version ElacticSearch : 2.3.3
version Swift : 1.13.1

Adding repository is OK and list it is OK too.

When i try to backup ES, this error occurs : 
{"error":{"root_cause":[{"type":"command_exception","reason":"Unable to execute the HTTP call or to convert the HTTP Response"}],"type":"command_exception","reason":"Unable to execute the HTTP call or to convert the HTTP Response","caused_by":{"type":"json_mapping_exception","reason":"Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")","caused_by":{"type":"illegal_argument_exception","reason":"Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")"}}}

When I list container with swift command, I can see some backups files on it, so it's seems works before this error.
Is that a bug ? if not, what to do to do not have this error ?

Best regards,

--
JLS

**Comment by nomoa** [comment]
This is certainly a bug in the plugin due to the new elasticsearch SecurityManager, unfortunately I did not encounter the issues when I tested.
I'll try to find some time to fix the issue.
In the meantime I think that the workaround would be to run elasticsearch with the security manager disabled.

**Comment by nomoa** [comment]
Unfortunately I can't reproduce the issue, could you give the full stacktrace (maybe you'll find more info in elasticsearch logs).

Also could you give me the output of curl -XGET 'elastic:9200/_snapshot' in case you've set particular options?

Thanks!

**Comment by jlesaux** [comment]
Hi,

Thanks for your quick answering.
To help investigating, I have full reset my hosts and had a fresh install on it.

*3 nodes*

## adding plugin (on all three nodes) ##
root@jlselastic:~# /usr/share/elasticsearch/bin/plugin install org.wikimedia.e
lasticsearch.swift/swift-repository-plugin/2.3.3
-> Installing org.wikimedia.elasticsearch.swift/swift-repository-plugin/2.3.3...
Trying https://download.elastic.co/org.wikimedia.elasticsearch.swift/swift-repository-plugin/swift-repository-plugin-2.3.3.zip ...
Trying https://search.maven.org/remotecontent?filepath=org/wikimedia/elasticsearch/swift/swift-repository-plugin/2.3.3/swift-repository-plugin-2.3.3.zip ...
Downloading ..............................................................................................................................................................................DONE
Verifying https://search.maven.org/remotecontent?filepath=org/wikimedia/elasticsearch/swift/swift-repository-plugin/2.3.3/swift-repository-plugin-2.3.3.zip checksums if available ...
Downloading .DONE
Installed swift-repository into /usr/share/elasticsearch/plugins/swift-repository

## adding repo ##
root@jlselastic:~# curl -XPUT 'http://localhost:9200/_snapshot/my_backup' -d '{
        "type": "swift",
        "settings": {
            "swift_url": "https://api.storage.local/auth/v1.0",
            "swift_container": "backupelastic",
            "swift_username": "jlesaux:admin",
            "swift_password": "osef"
        }
    }'
{"acknowledged":true}root@jlselastic:~# 

## restarting all ES node

## listing repo ##
root@jlselastic:~# curl -XGET 'http://localhost:9200/_snapshot/_all?pretty'
{
  "my_backup" : {
    "type" : "swift",
    "settings" : {
      "swift_username" : "jlesaux:admin",
      "swift_password" : "osef",
      "swift_url" : "https://api.storage.local/auth/v1.0",
      "swift_container" : "backupelastic"
    }
  }
}



root@jlselastic:~# curl -XPUT "localhost:9200/_snapshot/my_backup/snapshot_042?wait_for_completion=true"
{"error":{"root_cause":[{"type":"json_mapping_exception","reason":"json_mapping_exception: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")"}],"type":"command_exception","reason":"command_exception: Unable to execute the HTTP call or to convert the HTTP Response","caused_by":{"type":"json_mapping_exception","reason":"json_mapping_exception: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")","caused_by":{"type":"illegal_argument_exception","reason":"Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")"}}},"status":500}root@jlselastic:~# 




==> /var/log/elasticsearch/graylog.log <==
[2016-06-09 13:31:18,360][WARN ][rest.suppressed          ] /_snapshot/my_backup/snapshot_042 Params: {repository=my_backup, wait_for_completion=true, snapshot=snapshot_042}
RemoteTransportException[[jlstrusty02l][192.168.229.48:9300][cluster:admin/snapshot/create]]; nested: NotSerializableExceptionWrapper[command_exception: Unable to execute the HTTP call or to convert the HTTP Response]; nested: NotSerializableExceptionWrapper[json_mapping_exception: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")]; nested: IllegalArgumentException[Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")];
Caused by: NotSerializableExceptionWrapper[command_exception: Unable to execute the HTTP call or to convert the HTTP Response]; nested: NotSerializableExceptionWrapper[json_mapping_exception: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")]; nested: IllegalArgumentException[Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")];
        at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:58)
        at org.javaswift.joss.command.impl.core.AbstractSecureCommand.call(AbstractSecureCommand.java:31)
        at org.javaswift.joss.client.core.AbstractContainer.listDirectory(AbstractContainer.java:70)
        at org.javaswift.joss.client.core.ContainerDirectoryPaginationMap.list(ContainerDirectoryPaginationMap.java:23)
        at org.javaswift.joss.client.core.AbstractPaginationMap.listAllItems(AbstractPaginationMap.java:50)
        at org.javaswift.joss.client.core.AbstractContainer.listDirectory(AbstractContainer.java:75)
        at org.wikimedia.elasticsearch.swift.repositories.blobstore.SwiftBlobContainer.listBlobsByPrefix(SwiftBlobContainer.java:77)
        at org.wikimedia.elasticsearch.swift.repositories.blobstore.SwiftBlobContainer.listBlobsByPrefix(SwiftBlobContainer.java:24)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshots(BlobStoreRepository.java:398)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.finalizeSnapshot(BlobStoreRepository.java:376)
        at org.elasticsearch.snapshots.SnapshotsService$5.run(SnapshotsService.java:797)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: NotSerializableExceptionWrapper[json_mapping_exception: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")]; nested: IllegalArgumentException[Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")];
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCache2(StdDeserializerProvider.java:315)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCacheValueDeserializer(StdDeserializerProvider.java:290)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findValueDeserializer(StdDeserializerProvider.java:159)
        at org.codehaus.jackson.map.deser.BasicDeserializerFactory.createArrayDeserializer(BasicDeserializerFactory.java:234)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createDeserializer(StdDeserializerProvider.java:374)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCache2(StdDeserializerProvider.java:310)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCacheValueDeserializer(StdDeserializerProvider.java:290)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findValueDeserializer(StdDeserializerProvider.java:159)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findTypedValueDeserializer(StdDeserializerProvider.java:180)
        at org.codehaus.jackson.map.ObjectMapper._findRootDeserializer(ObjectMapper.java:2829)
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2728)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1909)
        at org.javaswift.joss.command.impl.container.ListDirectoryCommandImpl.getReturnObject(ListDirectoryCommandImpl.java:27)
        at org.javaswift.joss.command.impl.container.ListDirectoryCommandImpl.getReturnObject(ListDirectoryCommandImpl.java:15)
        at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:51)
        ... 13 more
Caused by: java.lang.IllegalArgumentException: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
        at org.codehaus.jackson.map.util.ClassUtil.checkAndFixAccess(ClassUtil.java:527)
        at org.codehaus.jackson.map.deser.BeanDeserializerFactory.constructDefaultValueInstantiator(BeanDeserializerFactory.java:829)
        at org.codehaus.jackson.map.deser.BeanDeserializerFactory.findValueInstantiator(BeanDeserializerFactory.java:553)
        at org.codehaus.jackson.map.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:696)
        at org.codehaus.jackson.map.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:636)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createDeserializer(StdDeserializerProvider.java:401)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCache2(StdDeserializerProvider.java:310)
        ... 27 more




rusty01l:~# curl -XGET "localhost:9200/_snapshot/my_backup/_all?pretty"
{
  "error" : {
    "root_cause" : [ {
      "type" : "json_mapping_exception",
      "reason" : "json_mapping_exception: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")"
    } ],
    "type" : "command_exception",
    "reason" : "command_exception: Unable to execute the HTTP call or to convert the HTTP Response",
    "caused_by" : {
      "type" : "json_mapping_exception",
      "reason" : "json_mapping_exception: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")"
      }
    }
  },
  "status" : 500
}


[2016-06-09 13:37:28,319][WARN ][rest.suppressed          ] /_snapshot/my_backup/_all Params: {pretty=, repository=my_backup, snapshot=_all}
RemoteTransportException[[jlstrusty02l][192.168.229.48:9300][cluster:admin/snapshot/get]]; nested: NotSerializableExceptionWrapper[command_exception: Unable to execute the HTTP call or to convert the HTTP Response]; nested: NotSerializableExceptionWrapper[json_mapping_exception: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")]; nested: IllegalArgumentException[Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")];
Caused by: NotSerializableExceptionWrapper[command_exception: Unable to execute the HTTP call or to convert the HTTP Response]; nested: NotSerializableExceptionWrapper[json_mapping_exception: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")]; nested: IllegalArgumentException[Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")];
        at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:58)
        at org.javaswift.joss.command.impl.core.AbstractSecureCommand.call(AbstractSecureCommand.java:31)
        at org.javaswift.joss.client.core.AbstractContainer.listDirectory(AbstractContainer.java:70)
        at org.javaswift.joss.client.core.ContainerDirectoryPaginationMap.list(ContainerDirectoryPaginationMap.java:23)
        at org.javaswift.joss.client.core.AbstractPaginationMap.listAllItems(AbstractPaginationMap.java:50)
        at org.javaswift.joss.client.core.AbstractContainer.listDirectory(AbstractContainer.java:75)
        at org.wikimedia.elasticsearch.swift.repositories.blobstore.SwiftBlobContainer.listBlobsByPrefix(SwiftBlobContainer.java:77)
        at org.wikimedia.elasticsearch.swift.repositories.blobstore.SwiftBlobContainer.listBlobsByPrefix(SwiftBlobContainer.java:24)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshots(BlobStoreRepository.java:398)
        at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:146)
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:80)
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:49)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:90)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$3.doRun(TransportMasterNodeAction.java:177)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: NotSerializableExceptionWrapper[json_mapping_exception: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")]; nested: IllegalArgumentException[Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")];
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCache2(StdDeserializerProvider.java:315)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCacheValueDeserializer(StdDeserializerProvider.java:290)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findValueDeserializer(StdDeserializerProvider.java:159)
        at org.codehaus.jackson.map.deser.BasicDeserializerFactory.createArrayDeserializer(BasicDeserializerFactory.java:234)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createDeserializer(StdDeserializerProvider.java:374)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCache2(StdDeserializerProvider.java:310)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCacheValueDeserializer(StdDeserializerProvider.java:290)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findValueDeserializer(StdDeserializerProvider.java:159)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findTypedValueDeserializer(StdDeserializerProvider.java:180)
        at org.codehaus.jackson.map.ObjectMapper._findRootDeserializer(ObjectMapper.java:2829)
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2728)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1909)
        at org.javaswift.joss.command.impl.container.ListDirectoryCommandImpl.getReturnObject(ListDirectoryCommandImpl.java:27)
        at org.javaswift.joss.command.impl.container.ListDirectoryCommandImpl.getReturnObject(ListDirectoryCommandImpl.java:15)
        at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:51)
        ... 17 more
Caused by: java.lang.IllegalArgumentException: Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
        at org.codehaus.jackson.map.util.ClassUtil.checkAndFixAccess(ClassUtil.java:527)
        at org.codehaus.jackson.map.deser.BeanDeserializerFactory.constructDefaultValueInstantiator(BeanDeserializerFactory.java:829)
        at org.codehaus.jackson.map.deser.BeanDeserializerFactory.findValueInstantiator(BeanDeserializerFactory.java:553)
        at org.codehaus.jackson.map.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:696)
        at org.codehaus.jackson.map.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:636)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createDeserializer(StdDeserializerProvider.java:401)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCache2(StdDeserializerProvider.java:310)
        ... 31 more


## check file on container via swift client ##
swift -A $URL -U $ACCOUNT -K $PASS list backupelastic
indices/graylog_0/meta-snapshot_042.dat
meta-snapshot_042.dat
snap-snapshot_042.dat
tests-xF301Q0LRRiDns35p9aKPQ/data--je3_z9_QXG67CAXtyGlLA.dat
tests-xF301Q0LRRiDns35p9aKPQ/data-u5BOYlQUTt6aqYCuni0aNw.dat
tests-xF301Q0LRRiDns35p9aKPQ/data-uxODC5WTThy6yjYdcvlCTg.dat
tests-xF301Q0LRRiDns35p9aKPQ/master.dat

I hope those traces will help.

Best regards,

**Comment by nomoa** [comment]
Would you mind to do a test with this version : https://drive.google.com/file/d/0Bzo2vOqfrXhJMUJZN2o4WVhkVUE/view?usp=sharing
I think I have fixed the underlying issue in joss.

Thanks!

**Comment by nomoa** [comment]
New version for testing https://drive.google.com/file/d/0Bzo2vOqfrXhJN21WUnBWVUFpSFk/view?usp=sharing

Thanks for your help.

**Comment by jlesaux** [comment]
Hi,

Thanks for that, after few tests with this new version swift-repository-plugin-2.3.3.1-SNAPSHOT.zip it's working without error.

*Backup*
curl -XPUT "localhost:9200/_snapshot/my_backup/monsnapshot?wait_for_completion=true"
{"snapshot":{"snapshot":"monsnapshot","version_id":2030399,"version":"2.3.3","indices":["graylog_0"],"state":"SUCCESS","start_time":"2016-06-15T10:09:16.672Z","start_time_in_millis":1465985356672,"end_time":"2016-06-15T10:09:22.881Z","end_time_in_millis":1465985362881,"duration_in_millis":6209,"failures":[],"shards":{"total":1,"failed":0,"successful":1}}}

In log file : 
[2016-06-15 12:09:22,880][INFO ][snapshots                ] [jlselastic] snapshot [my_backup:monsnapshot] is done

*Restore is ok too : *
 curl -XPOST "localhost:9200/_snapshot/my_backup/monsnapshot/_restore?pretty"
{
  "accepted" : true
}

in logs : 
[2016-06-15 13:13:19,539][INFO ][snapshots                ] [jlselastic] restore [my_backup:monsnapshot] is done

Thanks a lot :)

Best Regards,

--
Julien LE SAUX
