### ISSUE TITLE
Null Pointer 

### ISSUE THREAD

**Issue by aabed** [wikimedia/search-repository-swift#22]
{"error":{"root_cause":[{"type":"creation_exception","reason":"creation_exception: Guice creation errors:\n\n1) Error injecting constructor, java.lang.NullPointerException\n  at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(Unknown Source)\n  while locating org.wikimedia.elasticsearch.swift.repositories.SwiftRepository\n  while locating org.elasticsearch.repositories.Repository\n\n1 error"}],"type":"repository_exception","reason":"[my_backup] failed to create repository","caused_by":{"type":"creation_exception","reason":"creation_exception: Guice creation errors:\n\n1) Error injecting constructor, java.lang.NullPointerException\n  at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(Unknown Source)\n  while locating org.wikimedia.elasticsearch.swift.repositories.SwiftRepository\n  while locating org.elasticsearch.repositories.Repository\n\n1 error","caused_by":{"type":"null_pointer_exception","reason":null}}},"status":500}/ 

My settings
curl -XPUT 'http://elasticsearch:9200/_snapshot/my_backup' -d '{
        "type": "swift",
        "settings": {
            "swift_url": "https://identity.api.rackspacecloud.com/v2.0/",
            "swift_container": "my-container",
            "swift_username": "",
            "swift_password": ""
        }
    }'

**Comment by nomoa** [comment]
Hi,
could you provide the full stack trace from elasticsearch logs?
Thanks!

**Comment by johanek** [comment]
I have the same problem


    {
      "status": 500,
      "error": {
        "caused_by": {
          "caused_by": {
            "reason": null,
            "type": "null_pointer_exception"
          },
          "reason": "Guice creation errors:\n\n1) Error injecting constructor, java.lang.NullPointerException\n  at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(Unknown Source)\n  while locating org.wikimedia.elasticsearch.swift.repositories.SwiftRepository\n  while locating org.elasticsearch.repositories.Repository\n\n1 error",
          "type": "creation_exception"
        },
        "reason": "[swift] failed to create repository",
        "type": "repository_exception",
        "root_cause": [
          {
            "reason": "[swift] failed to create repository",
            "type": "repository_exception"
          }
        ]
      }
    }


My config:

    curl -XPUT http://localhost:9200/_snapshot/swift -d '{
        "type": "swift",
        "settings": {
            "swift_url": "https://redacted/v2.0/",
            "swift_container": "redacted",
            "swift_username": "redacted",
            "swift_password": "redacted",
            "swift_tenantname": "redacted"
        }
    }'


Elasticsearch logs:

     SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
     SLF4J: Defaulting to no-operation (NOP) logger implementation
     SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
     [2016-08-24 12:37:23,608][WARN ][repositories             ] [Death Adder] failed to create repository [swift][swift]
     org.elasticsearch.common.inject.CreationException: Guice creation errors:

     1) Error injecting constructor, java.lang.NullPointerException
       at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(Unknown Source)
       while locating org.wikimedia.elasticsearch.swift.repositories.SwiftRepository
       while locating org.elasticsearch.repositories.Repository

     1 error
          at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:360)
          at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
          at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
          at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:157)
          at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
          at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:404)
          at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:368)
          at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:55)
          at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:110)
          at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
          at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
          at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
          at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
          at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
          at java.lang.Thread.run(Thread.java:745)
     Caused by: java.lang.NullPointerException
          at org.javaswift.joss.command.impl.identity.AbstractSimpleAuthenticationCommandImpl.getReturnObject(AbstractSimpleAuthenticationCommandImpl.java:31)
          at org.javaswift.joss.command.impl.identity.AbstractSimpleAuthenticationCommandImpl.getReturnObject(AbstractSimpleAuthenticationCommandImpl.java:16)
          at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:51)
          at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:98)
          at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:27)
          at org.javaswift.joss.client.core.AbstractClient.authenticate(AbstractClient.java:35)
          at org.javaswift.joss.client.factory.AccountFactory.createAccount(AccountFactory.java:30)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService$1.run(SwiftService.java:60)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService$1.run(SwiftService.java:57)
          at java.security.AccessController.doPrivileged(Native Method)
          at org.wikimedia.elasticsearch.swift.SwiftPerms.exec(SwiftPerms.java:17)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService.createAccount(SwiftService.java:57)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService.swiftBasic(SwiftService.java:49)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftAccountFactory.createAccount(SwiftAccountFactory.java:16)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(SwiftRepository.java:66)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
          at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
          at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
          at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:54)
          at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
          at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)
          at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
          at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
          at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
          at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
          at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
          at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:879)
          at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
          at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
          ... 15 more
     [2016-08-24 12:37:23,610][WARN ][repositories             ] [Death Adder] failed to create repository [swift]
     RepositoryException[[swift] failed to create repository]; nested: CreationException[Guice creation errors:

     1) Error injecting constructor, java.lang.NullPointerException
       at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(Unknown Source)
       while locating org.wikimedia.elasticsearch.swift.repositories.SwiftRepository
       while locating org.elasticsearch.repositories.Repository

     1) Error injecting constructor, java.lang.NullPointerException
       at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(Unknown Source)
       while locating org.wikimedia.elasticsearch.swift.repositories.SwiftRepository
       while locating org.elasticsearch.repositories.Repository

     1 error
          at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:360)
          at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
          at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
          at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:157)
          at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
          at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:404)
          ... 11 more
     Caused by: java.lang.NullPointerException
          at org.javaswift.joss.command.impl.identity.AbstractSimpleAuthenticationCommandImpl.getReturnObject(AbstractSimpleAuthenticationCommandImpl.java:31)
          at org.javaswift.joss.command.impl.identity.AbstractSimpleAuthenticationCommandImpl.getReturnObject(AbstractSimpleAuthenticationCommandImpl.java:16)
          at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:51)
          at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:98)
          at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:27)
          at org.javaswift.joss.client.core.AbstractClient.authenticate(AbstractClient.java:35)
          at org.javaswift.joss.client.factory.AccountFactory.createAccount(AccountFactory.java:30)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService$1.run(SwiftService.java:60)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService$1.run(SwiftService.java:57)
          at java.security.AccessController.doPrivileged(Native Method)
          at org.wikimedia.elasticsearch.swift.SwiftPerms.exec(SwiftPerms.java:17)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService.createAccount(SwiftService.java:57)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService.swiftBasic(SwiftService.java:49)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftAccountFactory.createAccount(SwiftAccountFactory.java:16)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(SwiftRepository.java:66)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
          at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
          at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
          at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:54)
          at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
          at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)
          at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
          at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
          at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
          at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
          at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
          at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:879)
          at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
          at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
          ... 15 more
     [2016-08-24 12:37:23,612][WARN ][rest.suppressed          ] path: /_snapshot/swift, params: {repository=swift}
     RepositoryException[[swift] failed to create repository]; nested: CreationException[Guice creation errors:

     1) Error injecting constructor, java.lang.NullPointerException
       at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(Unknown Source)
       while locating org.wikimedia.elasticsearch.swift.repositories.SwiftRepository
       while locating org.elasticsearch.repositories.Repository

     1 error]; nested: NullPointerException;
          at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:411)
          at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:368)
          at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:55)
          at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:110)
          at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
          at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
          at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
          at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
          at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
          at java.lang.Thread.run(Thread.java:745)
     Caused by: org.elasticsearch.common.inject.CreationException: Guice creation errors:

     1) Error injecting constructor, java.lang.NullPointerException
       at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(Unknown Source)
       while locating org.wikimedia.elasticsearch.swift.repositories.SwiftRepository
       while locating org.elasticsearch.repositories.Repository

     1 error
          at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:360)
          at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
          at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
          at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:157)
          at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
          at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:404)
          ... 11 more
     Caused by: java.lang.NullPointerException
          at org.javaswift.joss.command.impl.identity.AbstractSimpleAuthenticationCommandImpl.getReturnObject(AbstractSimpleAuthenticationCommandImpl.java:31)
          at org.javaswift.joss.command.impl.identity.AbstractSimpleAuthenticationCommandImpl.getReturnObject(AbstractSimpleAuthenticationCommandImpl.java:16)
          at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:51)
          at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:98)
          at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:27)
          at org.javaswift.joss.client.core.AbstractClient.authenticate(AbstractClient.java:35)
          at org.javaswift.joss.client.factory.AccountFactory.createAccount(AccountFactory.java:30)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService$1.run(SwiftService.java:60)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService$1.run(SwiftService.java:57)
          at java.security.AccessController.doPrivileged(Native Method)
          at org.wikimedia.elasticsearch.swift.SwiftPerms.exec(SwiftPerms.java:17)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService.createAccount(SwiftService.java:57)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftService.swiftBasic(SwiftService.java:49)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftAccountFactory.createAccount(SwiftAccountFactory.java:16)
          at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(SwiftRepository.java:66)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
          at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
          at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
          at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:54)
          at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
          at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)
          at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
          at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
          at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
          at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
          at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
          at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:879)
          at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
          at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
          ... 15 more
